### ISSUE TITLE
ixa-pipe-nerc produces opennlp ArtifactSerializer error

### ISSUE THREAD

**Issue by wmkouw** [NLeSC/EviDENce#3]
Goal: run ixa-pipe-nerc-2.0.0 on .naf file using nerc-models-1.5.0. Followed instructions from README of https://github.com/ixa-ehu/ixa-pipe-nerc and ran: 
```
cat infile.txt | java -jar ../ixa-pipe-tok/target/ixa-pipe-tok-2.0.0-exec.jar tok -l nl | java -jar ../ixa-pipe-pos/target/ixa-pipe-pos-1.5.3-exec.jar tag -m ../ixa-pipe-pos/morph-models-1.5.0/nl/nl-pos-maxent-100-c5-autodict01-alpino.bin -lm ../ixa-pipe-pos/morph-models-1.5.0/nl/nl-lemma-perceptron-alpino.bin | java -jar target/ixa-pipe-nerc-2.0.0-exec.jar tag -m nerc-models-1.5.4/nl/nl-clusters-conll02.bin > outfile.naf
```

This is after downloading the other two repos, ixa-pipe-tok and ixa-pipe-pos, and installing all three modules using Maven. Models for pos and nerc are also downloaded and extracted according to github repo READMEs.

Problem: unable to find Apache OpenNLP ArtifactSerializer.
Stack trace:

Exception in thread "main" opennlp.tools.util.ext.ExtensionNotLoadedException: Unable to find implementation for opennlp.tools.util.model.ArtifactSerializer, the class or service eus.ixa.ixa.pipe.nerc.dict.BrownCluster$BrownClusterSerializer could not be located!
	at opennlp.tools.util.ext.ExtensionLoader.instantiateExtension(ExtensionLoader.java:122)
	at opennlp.tools.util.model.BaseModel.finishLoadingArtifacts(BaseModel.java:323)
	at opennlp.tools.util.model.BaseModel.loadModel(BaseModel.java:256)
	at opennlp.tools.util.model.BaseModel.<init>(BaseModel.java:179)
	at eus.ixa.ixa.pipe.ml.sequence.SequenceLabelerModel.<init>(SequenceLabelerModel.java:137)
	at eus.ixa.ixa.pipe.ml.StatisticalSequenceLabeler.loadModel(StatisticalSequenceLabeler.java:249)
	at eus.ixa.ixa.pipe.ml.StatisticalSequenceLabeler.<init>(StatisticalSequenceLabeler.java:73)
	at eus.ixa.ixa.pipe.nerc.Annotate.annotateOptions(Annotate.java:173)
	at eus.ixa.ixa.pipe.nerc.Annotate.<init>(Annotate.java:112)
	at eus.ixa.ixa.pipe.nerc.CLI.annotate(CLI.java:212)
	at eus.ixa.ixa.pipe.nerc.CLI.parseCLI(CLI.java:151)
	at eus.ixa.ixa.pipe.nerc.CLI.main(CLI.java:131)

**Comment by wmkouw** [comment]
This error masks a version mismatch error: ixa-pipe-nerc is version 2.0.0 while nerc-models is version 1.5.4.

This can be avoided in two ways:
1. Compiling ixa-pipe-nerc using an older version of Apache OpenNLP (https://opennlp.apache.org/) 
2. Download the full ixa-pipes-1.1.1 package (http://ixa2.si.ehu.es/ixa-pipes/models/ixa-pipes-1.1.1.tar.gz) and extract ixa-pipe-nerc-1.6.1 with nerc-models-1.6.1
